services:
  # Emulador de Cognito (cognito-local)
  cognito:
    image: jagregory/cognito-local:latest
    ports:
      - "9229:9229"
    environment:
      - REGION=us-east-1
      - DEBUG=1
  # LocalStack para otros servicios AWS (S3, DynamoDB, etc.)
  localstack:
    image: localstack/localstack
    ports:
        - "4566:4566"            # Puerto principal de LocalStack
        - "4510-4559:4510-4559"  # Puertos para servicios externos
    environment:
      - SERVICES=secretsmanager,s3,dynamodb,lambda  # Servicios a emular (ajusta según necesites)
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
